# Generated by Django 3.2.19 on 2023-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee1',
        ),
    ]
